kind: Service
apiVersion: v1
metadata:
  name: application
  labels:
    app: application
spec:
  type: ClusterIP
  selector:
    app: application
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
        version: v1
    spec:
      containers:
      - name: application
        image: application
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
